### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by alexszasz** [kuchin/awesome-cto#26]
[2016 European Software Development Salary Survey](https://www.oreilly.com/programming/free/files/2016-european-software-development-salary-survey.pdf) (O'Reilly)

https://www.oreilly.com/programming/free/files/2016-european-software-development-salary-survey.pdf

**Comment by ehmad11** [comment]
archive found: http://web.archive.org/web/20170412051943/https://www.oreilly.com/programming/free/files/2016-european-software-development-salary-survey.pdf

**Comment by Cather965** [comment]
Check any website or webpage for broken links in seconds. Find dead internal and external backlinks. No signup or download required. [mcdvoice](https://mcdvoice.me/)

**Comment by kuchin** [comment]
Thanks, updated!
