### ISSUE TITLE
Broken Link for "The Single Most Important Internal Email in the History of Amazon"

### ISSUE THREAD

**Issue by ranaaditya** [kuchin/awesome-cto#36]
this link for *[The Single Most Important Internal Email in the History of Amazon](https://www.sametab.com/blog/frameworks-for-remote-working)*.

public access is denied on this link.

Thanks,
rana

**Comment by kuchin** [comment]
Thank you! Updated to https://web.archive.org/web/20221127150918/https://pulseasync.com/operators/frameworks-for-remote-working/
