### ISSUE TITLE
Dead link in `44 engineering management lessons`

### ISSUE THREAD

**Issue by jmknoll** [kuchin/awesome-cto#4]
The article to the First Round Capital article on non-violent communication has moved. The article now lives [here](https://review.firstround.com/power-up-your-team-with-nonviolent-communication-principles).

**Comment by kuchin** [comment]
I'm not sure which original link are you referring to. In the code, "44 engineering management lessons" links to https://www.defmacro.org/2014/10/03/engman.html - which is working perfect. Please reopen the ticket if you meant some other link - but I need you to specify which one.

**Comment by jmknoll** [comment]
Its a link in the article itself. Point 34/44 has a link to an article on non-violent communication, which has moved to the URL referenced in my first comment.

I realize this is not part of your codebase, but worth referencing here for future readers, IMO.

**Comment by kuchin** [comment]
Oh, I get it now. Fixed, thanks!
