### ISSUE TITLE
Written standups

### ISSUE THREAD

**Issue by bobek** [kuchin/awesome-cto#6]
Hola, thank you for starting this awesome list. I had a great success with written standups. Even not that many people use them. Not sure where and even if you want to include the link to https://www.bobek.cz/blog/2021/written-standup/

**Comment by kuchin** [comment]
thanks, an interesting article! 
yet i'm not sure how effective it will look for the broader audience. and self-promoting is not the best option.

**Comment by bobek** [comment]
> and self-promoting is not the best option.

And that's exactly, why I have opened an issue and not PR :)
